<a href="https://colab.research.google.com/github/thanhduc17/python-lesson-k3/blob/main/bt_Numpy_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import cos,log10,sin,tan,sqrt,around

In [ ]:
def tao_1_vector_co_15_phan_tu_int():
  a = np.random.randint(1,10,size=10)
  return a


In [ ]:

def tinh_sin_cos_cb2_log(x):
  w =sin(x)
  d = cos (x)
  p = sqrt(x)
  e = log10(x)
  print(w)
  print(d)
  print(p)
  print(e)



In [ ]:
def tinh_lai_va_lam_tron_cau_2(x):
  w = sin(x)
  d = cos (x)
  p = sqrt(x)
  e = log10(x)
  print(np.around(w,2))
  print(np.around(d,2))
  print(np.around(p,2))
  print(np.around(e,2))



In [ ]:
def main():
  x = tao_1_vector_co_15_phan_tu_int()
  print(x)
  tinh_sin_cos_cb2_log(x)
  tinh_lai_va_lam_tron_cau_2(x)
if __name__ == "__main__":
  main()


[1 8 2 1 4 3 4 7 9 4]
[ 0.84147098  0.98935825  0.90929743  0.84147098 -0.7568025   0.14112001
 -0.7568025   0.6569866   0.41211849 -0.7568025 ]
[ 0.54030231 -0.14550003 -0.41614684  0.54030231 -0.65364362 -0.9899925
 -0.65364362  0.75390225 -0.91113026 -0.65364362]
[1.         2.82842712 1.41421356 1.         2.         1.73205081
 2.         2.64575131 3.         2.        ]
[0.         0.90308999 0.30103    0.         0.60205999 0.47712125
 0.60205999 0.84509804 0.95424251 0.60205999]
[ 0.84  0.99  0.91  0.84 -0.76  0.14 -0.76  0.66  0.41 -0.76]
[ 0.54 -0.15 -0.42  0.54 -0.65 -0.99 -0.65  0.75 -0.91 -0.65]
[1.   2.83 1.41 1.   2.   1.73 2.   2.65 3.   2.  ]
[0.   0.9  0.3  0.   0.6  0.48 0.6  0.85 0.95 0.6 ]


In [ ]:
import numpy as np 
import random 
from numpy import sin,cos,log,sqrt,tan
def ma_tran():
  A = np.random.randint(low=5, high=10,size=15).reshape((3,5))
  print("ma trận A :")
  return A
def cau3(x):
  
  a = np.around(np.sin(x),3)
  b = np.around(np.cos(x),3)
  c = np.around(np.tan(x),3)
  d = np.around(np.sqrt(x),3)
  e = np.around(np.log10(x),3)
  print("sin(A):\n",a)
  print("cos(A):\n",b)
  print("tan(A):\n",c)
  print("căn bậc hai của A :\n",d)
  print("log(A):\n",e)

In [ ]:
def main():
  A= ma_tran()
  x = np.array(A)
  print(x)
  cau3(x)
if __name__ == "__main__":
  main()

ma trận A :
[[7 5 8 5 5]
 [8 5 7 7 8]
 [5 6 6 6 7]]
sin(A):
[[ 0.657 -0.959  0.989 -0.959 -0.959]
 [ 0.989 -0.959  0.657  0.657  0.989]
 [-0.959 -0.279 -0.279 -0.279  0.657]]
cos(A):
[[ 0.754  0.284 -0.146  0.284  0.284]
 [-0.146  0.284  0.754  0.754 -0.146]
 [ 0.284  0.96   0.96   0.96   0.754]]
tan(A):
[[ 0.871 -3.381 -6.8   -3.381 -3.381]
 [-6.8   -3.381  0.871  0.871 -6.8  ]
 [-3.381 -0.291 -0.291 -0.291  0.871]]
căn bậc hai của A :
[[2.646 2.236 2.828 2.236 2.236]
 [2.828 2.236 2.646 2.646 2.828]
 [2.236 2.449 2.449 2.449 2.646]]
log(A)
[[0.845 0.699 0.903 0.699 0.699]
 [0.903 0.699 0.845 0.845 0.903]
 [0.699 0.778 0.778 0.778 0.845]]
