<a href="https://colab.research.google.com/github/thanhduc17/python-lesson-k3/blob/main/btvn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
X=[]
for i in range(0,7) :
  i+=1
  x = float(input("mời nhập phần tử của x  "))
  print("x",i,"=",x)
  X.append(x)

print("X =",X)

mời nhập phần tử của x  3
x 1 = 3.0
mời nhập phần tử của x  2
x 2 = 2.0
mời nhập phần tử của x  1
x 3 = 1.0
mời nhập phần tử của x  4
x 4 = 4.0
mời nhập phần tử của x  3
x 5 = 3.0
mời nhập phần tử của x  2
x 6 = 2.0
mời nhập phần tử của x  4
x 7 = 4.0
X = [3.0, 2.0, 1.0, 4.0, 3.0, 2.0, 4.0]


In [ ]:
X = []
import random
for i in range(0,30) :
  i+=1
  x = random.randint(-10, 10)
  print("x",i,"=",x)
  X.append(x)
  
print("X =",X)



x 1 = 10
x 2 = -6
x 3 = -7
x 4 = -7
x 5 = 5
x 6 = 7
x 7 = 7
x 8 = -9
x 9 = -5
x 10 = 10
x 11 = 6
x 12 = -2
x 13 = 0
x 14 = -1
x 15 = 3
x 16 = 8
x 17 = -8
x 18 = 4
x 19 = 2
x 20 = 5
x 21 = -4
x 22 = -5
x 23 = 5
x 24 = 5
x 25 = -6
x 26 = 5
x 27 = -9
x 28 = -7
x 29 = 2
x 30 = -6
X = [10, -6, -7, -7, 5, 7, 7, -9, -5, 10, 6, -2, 0, -1, 3, 8, -8, 4, 2, 5, -4, -5, 5, 5, -6, 5, -9, -7, 2, -6]


In [ ]:
X = []
import random
for i in range(0,30) :
  i+=1
  n =(-5.6,6.9)
  x = random.uniform(-5.7,6.9)
  print("x",i,"=",x)
  X.append(x)
print("X =",X)

x 1 = -0.08778610474445969
x 2 = 5.410389648859067
x 3 = 0.5824219365521079
x 4 = 4.05684661894685
x 5 = -1.6233286101234494
x 6 = -1.05139270094035
x 7 = 3.36144691378174
x 8 = 4.630565752532319
x 9 = -4.620640632288117
x 10 = 2.881267613218813
x 11 = -4.8911255315248425
x 12 = 0.31615439161924463
x 13 = 1.163423607133712
x 14 = 1.7600548477273765
x 15 = -3.053005754633706
x 16 = 2.778730516208314
x 17 = -3.3960450523791708
x 18 = -4.440407949528241
x 19 = 0.19020709029881733
x 20 = 1.8949088876288727
x 21 = -3.2372857735767027
x 22 = -2.0363228537210234
x 23 = 3.6768148702039793
x 24 = 3.386294590851395
x 25 = 1.6758254337766516
x 26 = 1.3169552547631893
x 27 = 3.812298483625308
x 28 = 2.3832588787745577
x 29 = 5.410379703149384
x 30 = 1.09904297920591
X = [-0.08778610474445969, 5.410389648859067, 0.5824219365521079, 4.05684661894685, -1.6233286101234494, -1.05139270094035, 3.36144691378174, 4.630565752532319, -4.620640632288117, 2.881267613218813, -4.8911255315248425, 0.316154391619

In [ ]:
import numpy as np
import random
X=[]
a = float(input("mời nhập số thực a ="))

for i in range(0,10) :
  i+=1
  x = random.randint(0,100)
  X.append(x)
print("X =",X)

X1 = np.array(X)
t = a*X1

print(a,"*",X1,"=",t)

mời nhập số thực a =2
X = [92, 77, 55, 23, 92, 69, 11, 43, 19, 70]
2.0 * [92 77 55 23 92 69 11 43 19 70] = [184. 154. 110.  46. 184. 138.  22.  86.  38. 140.]


In [ ]:
import random 
x1 = []
x2 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,1000 )
    x4=random.randint(0,1000 )
    x1.append(x)
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)

t = ư1+ ư2
a = ư1- ư2
print(t,"\n",a)

[980, 239, 388, 684, 391, 886, 587, 477, 441, 370, 962, 621, 568, 194, 527]
[689, 894, 973, 19, 658, 1000, 946, 884, 437, 654, 414, 512, 175, 24, 351]
[1669 1133 1361  703 1049 1886 1533 1361  878 1024 1376 1133  743  218
  878] 
 [ 291 -655 -585  665 -267 -114 -359 -407    4 -284  548  109  393  170
  176]


In [ ]:
x1 = []
x2 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x4=random.randint(0,10 )
    x1.append(x)
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)
t = ư1*ư2
print(t,"\n")

[4, 0, 9, 8, 4, 8, 10, 4, 3, 7, 10, 2, 9, 9, 3]
[10, 8, 3, 4, 9, 7, 3, 2, 1, 5, 2, 9, 1, 0, 9]
[40  0 27 32 36 56 30  8  3 35 20 18  9  0 27] 



In [ ]:
import random
x = []
y = []
tvh = 0 
for i in range(0,15):
    i+=1
    x1=random.randint(0,10 )
    y2=random.randint(0,10 )
    x.append(x1)
    y.append(y2)
    tvh += x[i]
print(x)
print(y)
print(tvh,"\n")

IndexError: ignored

In [ ]:
import numpy as np
x1 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x1.append(x) 
print(x1)
ư1 = np.array(x1)
x=ư1.reshape(3,5)
print(x)

[5, 10, 7, 7, 4, 9, 1, 8, 0, 1, 9, 7, 7, 0, 5]
[[ 5 10  7  7  4]
 [ 9  1  8  0  1]
 [ 9  7  7  0  5]]


In [ ]:
import numpy as np
x1 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x1.append(x) 
print(x1)
a = float(input())
ư1 = np.array(x1)
x=ư1.reshape(3,5)
t = a*x
print(x)
print(t)


[4, 0, 6, 4, 9, 8, 8, 4, 6, 10, 6, 7, 10, 8, 4]
2.5
[[ 4  0  6  4  9]
 [ 8  8  4  6 10]
 [ 6  7 10  8  4]]
[[10.   0.  15.  10.  22.5]
 [20.  20.  10.  15.  25. ]
 [15.  17.5 25.  20.  10. ]]


In [ ]:
x1 = []
x2 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x4=random.randint(0,10 )
    x1.append(x)
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)
x=ư1.reshape(3,5)
x1=ư2.reshape(3,5)
t=x+x1
print(x,"\n",x1)
print(t,"\n")

[4, 1, 9, 9, 2, 4, 2, 0, 2, 9, 0, 8, 0, 1, 1]
[2, 6, 4, 7, 10, 4, 7, 10, 1, 9, 3, 10, 8, 2, 7]
[[4 1 9 9 2]
 [4 2 0 2 9]
 [0 8 0 1 1]] 
 [[ 2  6  4  7 10]
 [ 4  7 10  1  9]
 [ 3 10  8  2  7]]
[[ 6  7 13 16 12]
 [ 8  9 10  3 18]
 [ 3 18  8  3  8]] 



In [ ]:
x1 = []
x2 = []
for i in range(0,12):
    i+=1
    x=random.randint(0,10 )
    x1.append(x)
for i in range(0,20):
    i+=1
    x4=random.randint(0,10 )
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)
x=ư1.reshape(3,4)
x1=ư2.reshape(4,5)
t=x@x1
print(x,"\n",x1)
print(t,"\n")

[4, 8, 5, 4, 5, 3, 10, 2, 5, 5, 2, 10]
[3, 3, 5, 8, 0, 5, 1, 4, 10, 1, 2, 6, 9, 9, 2, 5, 1, 4, 6, 10]
[[ 4  8  5  4]
 [ 5  3 10  2]
 [ 5  5  2 10]] 
 [[ 3  3  5  8  0]
 [ 5  1  4 10  1]
 [ 2  6  9  9  2]
 [ 5  1  4  6 10]]
[[ 82  54 113 181  58]
 [ 60  80 135 172  43]
 [ 94  42 103 168 109]] 

