<a href="https://colab.research.google.com/github/thanhduc17/python-lesson-k3/blob/main/btvn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bài 1: Một vector x ∈ R^n
(hay còn gọi là 1 tensor hạng 1) được diễn đạt dưới dạng x = [x0; x1; ... ; xn−1]. 

Hãy viết chương trình nhập dữ liệu cho 1 vector x ∈ R^7 từ bàn phím.



In [2]:
X=[]
for i in range(0,7) :
  i+=1
  x = float(input("mời nhập phần tử của x  "))
  print("x",i,"=",x)
  X.append(x)

print("X =",X)

mời nhập phần tử của x  2
x 1 = 2.0
mời nhập phần tử của x  3
x 2 = 3.0
mời nhập phần tử của x  3
x 3 = 3.0
mời nhập phần tử của x  2
x 4 = 2.0
mời nhập phần tử của x  1
x 5 = 1.0
mời nhập phần tử của x  4
x 6 = 4.0
mời nhập phần tử của x  5
x 7 = 5.0
X = [2.0, 3.0, 3.0, 2.0, 1.0, 4.0, 5.0]


Bài 2: Thay vì phải nhập dữ liệu bằng tay, chúng ta có thể sinh ngẫu nhiên giá trị cho từng phần tử xi bằng cách sử dụng thư viện random.

Hãy viết chương trình sinh giá trị ngẫu nhiên cho vector x ∈ R^30 với xi ∈ N và xi ∈ [−10, 10].

Tham khảo hàm sinh ngẫu nhiên số nguyên. In kết quả ra màn hình.


In [3]:
X = []
import random
for i in range(0,30) :
  i+=1
  x = random.randint(-10, 10)
  print("x",i,"=",x)
  X.append(x)
  
print("X =",X)



x 1 = -10
x 2 = -6
x 3 = -10
x 4 = -8
x 5 = 10
x 6 = -7
x 7 = -4
x 8 = -2
x 9 = -1
x 10 = -5
x 11 = 10
x 12 = 4
x 13 = 9
x 14 = 3
x 15 = -6
x 16 = 9
x 17 = -8
x 18 = -10
x 19 = -7
x 20 = 0
x 21 = 2
x 22 = 4
x 23 = 5
x 24 = 10
x 25 = -2
x 26 = 2
x 27 = 9
x 28 = -4
x 29 = -9
x 30 = -8
X = [-10, -6, -10, -8, 10, -7, -4, -2, -1, -5, 10, 4, 9, 3, -6, 9, -8, -10, -7, 0, 2, 4, 5, 10, -2, 2, 9, -4, -9, -8]


Bài 3: Tương tự bài 2, hãy viết chương trình sinh ngẫu nhiên giá trị cho vector x ∈ R^30 với
xi ∈ [−5.7, 6.9] và in kết quả ra màn hình.

Tham khảo hàm sinh ngẫu nhiên số thực.


In [4]:
X = []
import random
for i in range(0,30) :
  i+=1
  n =(-5.6,6.9)
  x = random.uniform(-5.7,6.9)
  print("x",i,"=",x)
  X.append(x)
print("X =",X)

x 1 = 4.0609706457513335
x 2 = 3.1188506749431317
x 3 = 1.4943564775426363
x 4 = 5.160341595740165
x 5 = -3.1052603337812963
x 6 = 0.223033843415954
x 7 = 0.6674419404411367
x 8 = 6.5339172723233725
x 9 = 1.5069437659542322
x 10 = -1.0066278705659482
x 11 = 4.9344772418571585
x 12 = 4.013496125843942
x 13 = -1.369214043431949
x 14 = -0.5979823158972515
x 15 = -4.909067781988263
x 16 = 5.863771778169171
x 17 = 0.5491407504177728
x 18 = -5.0733758830873334
x 19 = -0.5549268218889898
x 20 = -2.1842073757239504
x 21 = 6.397231168295478
x 22 = 2.834362766670881
x 23 = -4.324776744515632
x 24 = -1.6726089349523958
x 25 = 1.0118967452010885
x 26 = 6.167361334919227
x 27 = 3.1146814653086023
x 28 = -4.0342813444756676
x 29 = -5.0629721234517495
x 30 = -3.038730740475074
X = [4.0609706457513335, 3.1188506749431317, 1.4943564775426363, 5.160341595740165, -3.1052603337812963, 0.223033843415954, 0.6674419404411367, 6.5339172723233725, 1.5069437659542322, -1.0066278705659482, 4.9344772418571585, 4.

Bài 4: Phép nhân 1 đại lượng vô hướng α với 1 vector x được định nghĩa là:

α . x = α[x0; x1; ... ; xn−1] = [αx0; αx1; ... ; αxn−1]

Hãy viết chương trình thực hiện phép nhân này với số thực α nhập từ bàn phím, x ∈ R^10 được sinh ngẫu nhiên.

Kết quả xuất ra màn hình.


In [5]:
import numpy as np
import random
X=[]
a = float(input("mời nhập số thực a ="))

for i in range(0,10) :
  i+=1
  x = random.randint(0,100)
  X.append(x)
print("X =",X)

X1 = np.array(X)
t = a*X1
print(a,"*",X1,"=",t)

mời nhập số thực a =4.6
X = [83, 25, 69, 57, 14, 6, 13, 21, 68, 29]
4.6 * [83 25 69 57 14  6 13 21 68 29] = [381.8 115.  317.4 262.2  64.4  27.6  59.8  96.6 312.8 133.4]


Bài 5: Phép cộng của 2 vector x, y ∈ R^n được định nghĩa là

x + y = [x0 + yo; x1 + y1; ... ; xn−1 + yn−1]

Hãy viết chương trình thực hiện phép cộng và phép trừ 2 vector x, y ∈ R^15. 

In kết quả ra màn hình.


In [6]:
import random 
x1 = []
x2 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,1000 )
    x4=random.randint(0,1000 )
    x1.append(x)
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)

t = ư1+ ư2
a = ư1- ư2
print(t,"\n",a)

[772, 283, 408, 202, 148, 556, 841, 265, 360, 226, 346, 917, 83, 582, 817]
[358, 388, 644, 522, 101, 902, 254, 873, 190, 944, 780, 340, 754, 522, 914]
[1130  671 1052  724  249 1458 1095 1138  550 1170 1126 1257  837 1104
 1731] 
 [ 414 -105 -236 -320   47 -346  587 -608  170 -718 -434  577 -671   60
  -97]


Bài 6: Phép nhân elementwise multiplication của 2 vector x, y ∈ R^n được định nghĩa là:

x°y = [x0; x1; ... ; xn−1] ∙ [y0; y1; ... ; yn−1] = [x0. y0; x1. y1; ... ; xn−1. yn−1]

Hãy viết chương trình thực hiện sinh ngẫu nhiên 2 vector x, y ∈ R^10 và thực hiện phép nhân elementwise multiplication x°y và in kết quả ra màn hình.

In [16]:
x1 = []
x2 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x4=random.randint(0,10 )
    x1.append(x)
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)
print(np.multiply(ư1,ư2))

[10, 7, 0, 0, 7, 5, 10, 0, 5, 4, 0, 5, 2, 2, 4]
[10, 1, 6, 6, 10, 2, 3, 1, 9, 10, 7, 2, 0, 2, 2]
[100   7   0   0  70  10  30   0  45  40   0  10   0   4   8]


Bài 7: Tích vô hướng của 2 vector x, y ∈ R^n được định nghĩa là

x. y = ∑xi. yi = x0. y0 + x1. y1 + xn−1. yn−1
n−1

i=0

Hãy viết chương trình thực hiện tính tích vô hướng 2 vector x, y ∈ R^10 và in kết quả ra màn hình.


In [15]:
import random
x = []
y = []
for i in range(15):
    x1=random.randint(0,10 )
    y1=random.randint(0,10 )
    x.append(x1)
    y.append(y1)
print(x)
print(y)
ư1 = np.array(x)
ư2 = np.array(y)
t = ư1*ư2
print(t,"\n")

[1, 3, 10, 0, 5, 1, 7, 0, 8, 5, 9, 10, 0, 4, 10]
[7, 8, 1, 1, 5, 6, 7, 10, 6, 1, 5, 8, 4, 4, 9]
[ 7 24 10  0 25  6 49  0 48  5 45 80  0 16 90] 



Bài 8: Một ma trận A ∈ R
m×n (hay còn gọi là 1 tensor hạng 2) với aij ∈ R
Hãy viết chương trình sinh ngẫu nhiên ma trận A ∈ R
3×5. 

In ma trận A ra màn hình và in phần tử a23 ra màn hình.


In [9]:
import numpy as np
x1 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x1.append(x) 
print(x1)
ư1 = np.array(x1)
x=ư1.reshape(3,5)
print(x)

[8, 4, 2, 7, 9, 5, 3, 0, 7, 1, 1, 8, 4, 3, 10]
[[ 8  4  2  7  9]
 [ 5  3  0  7  1]
 [ 1  8  4  3 10]]


Bài 9: Phép nhân vô hướng với ma trận A được định nghĩa là:
α. A   với α, aij ∈ R

Hãy viết chương trình tính tích nêu trên với α là số thực nhập vào từ bàn phím và ma trận
A ∈ R
3×5 được sinh ngẫu nhiên. 

In kết quả ra màn hình.


In [10]:
import numpy as np
x1 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x1.append(x) 
print(x1)
a = float(input())
ư1 = np.array(x1)
x=ư1.reshape(3,5)
t = a*x
print(x)
print(t)


[8, 8, 10, 1, 9, 9, 2, 6, 4, 3, 4, 4, 1, 2, 10]
4
[[ 8  8 10  1  9]
 [ 9  2  6  4  3]
 [ 4  4  1  2 10]]
[[32. 32. 40.  4. 36.]
 [36.  8. 24. 16. 12.]
 [16. 16.  4.  8. 40.]]


Bài 10: Phép cộng 2 ma trận A, B ∈ R m×n được định nghĩa là:

A + B 
Hãy viết chương trình tính phép cộng 2 ma trận A, B ∈ R3×5 và in kết quả ra màn hình.

In [11]:
x1 = []
x2 = []
for i in range(0,15):
    i+=1
    x=random.randint(0,10 )
    x4=random.randint(0,10 )
    x1.append(x)
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)
x=ư1.reshape(3,5)
x1=ư2.reshape(3,5)
t=x+x1
print(x,"\n",x1)
print(t,"\n")

[9, 9, 4, 7, 6, 3, 1, 6, 6, 8, 1, 10, 7, 5, 4]
[2, 0, 9, 4, 10, 10, 7, 3, 6, 6, 1, 2, 2, 0, 5]
[[ 9  9  4  7  6]
 [ 3  1  6  6  8]
 [ 1 10  7  5  4]] 
 [[ 2  0  9  4 10]
 [10  7  3  6  6]
 [ 1  2  2  0  5]]
[[11  9 13 11 16]
 [13  8  9 12 14]
 [ 2 12  9  5  9]] 



Bài 11: Phép nhân 2 ma trận A ∈ Rm×k và B ∈ Rk×n được định nghĩa là:

C = A. B ∈ Rm×n


Hãy viết chương trình tính tích 2 ma trận A ∈ R3×4 và B ∈ R4×5

In [13]:
x1 = []
x2 = []
for i in range(12):
    x=random.randint(0,10 )
    x1.append(x)
for i in range(20):
    i+=1
    x4=random.randint(0,10 )
    x2.append(x4)
print(x1)
print(x2)
ư1 = np.array(x1)
ư2 = np.array(x2)
x=ư1.reshape(3,4)
x1=ư2.reshape(4,5)
t=x@x1
print(x,"\n",x1)
print(t,"\n")

[8, 2, 9, 9, 2, 0, 1, 2, 2, 9, 3, 4]
[2, 7, 7, 2, 6, 4, 9, 0, 7, 10, 7, 7, 2, 3, 2, 1, 2, 1, 1, 10]
[[8 2 9 9]
 [2 0 1 2]
 [2 9 3 4]] 
 [[ 2  7  7  2  6]
 [ 4  9  0  7 10]
 [ 7  7  2  3  2]
 [ 1  2  1  1 10]]
[[ 96 155  83  66 176]
 [ 13  25  18   9  34]
 [ 65 124  24  80 148]] 

